theme: jekyll-theme-tactile
title: My Presentation Slides
description: Bookmark this to keep an eye on my presentations!
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge